# Utilisation de l'h\u00F4te priv\u00E9 avec param\u00E8tres de reconnexion automatique
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forcer la synchronisation Hibernate uniquement si la connexion est \u00E9tablie
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port r\u00E9seau dynamique pour Railway
server.port=${PORT:8080}

