spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forcer le port dynamique r\u00E9seau de Railway
server.port=${PORT:8080}

# Permet \u00E0 Hibernate de synchroniser l'arborescence des tables au d\u00E9marrage
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
