logging.level.root=DEBUG

# Configuration R\u00E9seau (Indispensable pour Railway)
server.port=${PORT:8080}
server.address=0.0.0.0

# Configuration de la Base de Donn\u00E9es
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# G\u00E9n\u00E9ration des Tables
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

spring.jpa.properties.hibernate.globally_quoted_identifiers=true

